minecraft_version=1.21.1
minecraft_versions=1.21.1
v_name_override=
java_version=25

# Mod properties
mod_id=t_and_t
mod_version=1.13.10

# Fabric
fabric_loader_min_version=0.18.5

# NeoForge
neoforge_min_version=21.1.230

# Dependencies
cristellib_version=3.1.7

# Mod Properties
mod_name=Towns and Towers

### https://creativecommons.org/licenses/by-nc-sa/4.0/
license=CC-BY-NC-ND-4.0
mod_author1=Kubek
mod_author2=Biban_Auriu
mod_author3=Cristelknight999
description=Spice up your world with new villages, pillager outposts, and even new ships!
homepage=https://modrinth.com/mod/towns-and-towers
discord=https://discord.gg/G2UJ2FAuYh

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true