modLoader = "javafml"
loaderVersion = "[2,)"

license="${license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_author1} and ${mod_author2}, ${mod_author3}"
    displayURL="${homepage}"
    logoFile= "pack.png"
    description="${description}"
    displayTest="IGNORE_ALL_VERSION"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_min_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="cristellib"
    type="required"
    versionRange="[${cristellib_version},)"
    ordering="NONE"
    side="BOTH"